XWIKI-13196
```
java.lang.IllegalArgumentException: An Entity Reference name cannot be null or empty
	at org.xwiki.model.reference.EntityReference.setName(EntityReference.java:186)
	at org.xwiki.model.reference.EntityReference.<init>(EntityReference.java:154)
	at org.xwiki.model.reference.AttachmentReference.<init>(AttachmentReference.java:68)
	at com.xpn.xwiki.doc.XWikiAttachment.getReference(XWikiAttachment.java:156)
	at org.xwiki.search.solr.internal.reference.DocumentSolrReferenceResolver.addAttachmentsReferences(DocumentSolrReferenceResolver.java:139)
	at org.xwiki.search.solr.internal.reference.DocumentSolrReferenceResolver.getReferences(DocumentSolrReferenceResolver.java:121)
	at org.xwiki.search.solr.internal.reference.DefaultSolrReferenceResolver.getReferences(DefaultSolrReferenceResolver.java:163)
	at org.xwiki.search.solr.internal.DefaultSolrIndexer$Resolver.runInternal(DefaultSolrIndexer.java:213)
	at com.xpn.xwiki.util.AbstractXWikiRunnable.run(AbstractXWikiRunnable.java:131)
	at java.lang.Thread.run(Thread.java:744)
```

# Frame 1 & 2 & 3 & 4
```diff
+ REPLICATED
```

# Frame 5
## Line is not covered
The target call is private. Evocrash found a public caller to target call (`getReferences`).
Evocrash got stock in line 90 of `getReferences`, and it did not achieve to the line which target call is called.
The line 90 is :
```
if (xcontext.getWiki().exists(documentReference, xcontext))
```
and `xcontext` is defined before that:
```
XWikiContext xcontext = this.xcontextProvider.get();
```
and `xcontextProvider` is an injected object. Evocrash tried to generate proper state for `xcontextProvider`, but it was unsuccessful.

# Frame 6
## Line is not covered
Target call is `getReferences`. look to description of Frame 5.

# Frame 7
## Line is covered
But ... NPE has been thrown in target line.
target line is:
```
wikis = new ArrayList<String>(this.wikiDescriptorManager.getAllIds());

```
`wikiDescriptorManager` is injected to CUT, and Evocrash could not mock it in a proper way for `java.util.ArrayList`.

# Frame 8
Evocrash crashed before starting search without any error message.
because of **inner classes**.

# Frame 9
## Line is not covered
Evocrash got stock in Line 50 which is before target line.
In line 50 we have call to method out of CUT, adn that method have another call to another class. Finally, Evocrash got stock in one of the classes which had a variable which needs a setter method to call.
Evocrash did not call methods of other classes unless they were used as inputs for calling target method in CUT.


